version: '3'
services:
  db:
    image:  postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}